yarnPath: .yarn/releases/yarn-3.2.0.cjs
# AWS teams seem to not bother defining their dependencies properly; they just assume they're installed. This is incompatible with yarn v2+. We massage them here
packageExtensions:
  "@aws-crypto/sha256-browser@*":
    dependencies:
      "@aws-sdk/util-utf8-browser": "*"
  "@aws-amplify/api@*":
    dependencies:
      "@aws-amplify/auth": "*"
      "@aws-amplify/cache": "*"
      "@aws-amplify/core": "*"
  "@aws-amplify/datastore@*":
    dependencies:
      "@aws-amplify/cache": "*"
      "@aws-amplify/api-graphql": "*"
      "crypto-js": "*"
  "@aws-amplify/storage@*":
    dependencies:
      "@aws-sdk/fetch-http-handler": "*"
      "@aws-sdk/protocol-http": "*"
      "@aws-sdk/querystring-builder": "*"
  "@aws-amplify/ui-components@*":
    dependencies:
      "@aws-amplify/auth": "*"
      "@aws-amplify/core": "*"
      "@aws-amplify/interactions": "*"
      "@aws-amplify/storage": "*"
  "@aws-amplify/ui-react@*":
    dependencies:
      "@aws-amplify/auth": "*"
      "@aws-amplify/geo": "*"
      "@aws-amplify/core": "*"
      "aws-amplify": "*"
      "xstate": "*"
  "aws-appsync-auth-link@*":
    peerDependencies:
      "graphql": "*"
  "aws-appsync-subscription-link@*":
    peerDependencies:
      "graphql": "*"
    dependencies:
      "uuid": "*"
  "react-map-gl@*":
    peerDependencies:
      "react-dom": "*"
  "eslint-config-react-app@*":
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "react-scripts@*":
    peerDependencies:
      "eslint-plugin-prettier": "*"
      "eslint-plugin-json": "*"
      "eslint-plugin-unused-imports": "*"
